import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";
import typography from "@tailwindcss/typography";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,ts}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#0c0e10",
        surface: "#f9f9fb",
        error: "#a8364b",
        "on-secondary-fixed-variant": "#5f586e",
        "on-primary-container": "#1e0050",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed": "#423c50",
        secondary: "#625c71",
        "on-surface": "#2e3336",
        "inverse-on-surface": "#9c9d9f",
        background: "#f9f9fb",
        "tertiary-dim": "#6e4664",
        "on-error": "#fff7f7",
        "on-background": "#2e3336",
        "surface-container-highest": "#dfe3e7",
        "inverse-primary": "#a67ffd",
        "on-secondary-container": "#554f63",
        "on-secondary": "#fdf7ff",
        "primary-fixed": "#a67ffd",
        "on-tertiary-fixed": "#45223e",
        "primary-container": "#a67ffd",
        "surface-container": "#eceef1",
        outline: "#777b7f",
        "on-primary": "#fdf7ff",
        "tertiary-fixed-dim": "#dfadd0",
        "on-tertiary-container": "#5b3552",
        "secondary-container": "#e8def8",
        "secondary-fixed": "#e8def8",
        "surface-bright": "#f9f9fb",
        "secondary-fixed-dim": "#d9d0ea",
        primary: "#6d46c1",
        "surface-container-high": "#e6e8ec",
        "primary-fixed-dim": "#9872ef",
        tertiary: "#7b5271",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#6e0523",
        "error-container": "#f97386",
        "tertiary-fixed": "#edbade",
        "tertiary-container": "#edbade",
        "on-tertiary-fixed-variant": "#653e5c",
        "outline-variant": "#aeb2b6",
        "on-primary-fixed-variant": "#2b006b",
        "surface-variant": "#dfe3e7",
        "primary-dim": "#6138b4",
        "secondary-dim": "#565065",
        "error-dim": "#6b0221",
        "surface-tint": "#6d46c1",
        "surface-dim": "#d7dadf",
        "on-tertiary": "#fff7f9",
        "on-surface-variant": "#5b6063",
        "on-primary-fixed": "#000000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [forms, containerQueries, typography],
};
